# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
contracts:
  - name: commbankdoteth
    handler: src/EventHandlers.ts
    events:
      - event: LeafInserted(uint256 indexed leafIndex, bytes32 indexed leafValue)
      - event: NotePayload(bytes encryptedNote)
      - event: NullifierUsed(bytes32 indexed nullifier)
      - event: RoleAdminChanged(bytes32 indexed role, bytes32 indexed previousAdminRole, bytes32 indexed newAdminRole)
      - event: RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)
      - event: RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)
chains:
  # Ethereum Mainnet
  - id: 1
    start_block: 0
    contracts:
      - name: commbankdoteth
        address:
          - 0x5eEAAE6dA50C2cBC94F8A0B25a1D9bAD8225db1e
  # Arbitrum Sepolia
  - id: 421614
    start_block: 0
    contracts:
      - name: commbankdoteth
        address:
          - 0xC0e0C9DC1DE67B7f6434FfdDf2A33300ed6f49E3
unordered_multichain_mode: true
preload_handlers: true
